---
format_version: '23'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: flutter

triggers:
  push:
  - branch: main
    workflow: android_firebase
  pull_request:
  - source_branch: "*"
    workflow: android_firebase

app:
  envs:
  - BITRISE_FLUTTER_PROJECT_LOCATION: "."
    opts:
      is_expand: false
  - BITRISE_PROJECT_PATH: android/build.gradle.kts
    opts:
      is_expand: false

workflows:
  android_firebase:
    description: Build Android APK for Tracker Costs with Firebase App Distribution
    steps:
    
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    
    - git-clone@8: {}
    
    - flutter-installer@0:
        inputs:
        - version: stable
        - is_update: 'false'
    
    - restore-dart-cache@2: {}
    
    - script@1:
        title: Flutter packages get
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            echo "Installing Flutter dependencies..."
            flutter pub get
            echo "Dependencies installed"
    
    - script@1:
        title: Flutter analyze
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            echo "Running Flutter analyze..."
            flutter analyze || true
        is_always_run: false
    
    - script@1:
        title: Run Flutter tests
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            echo "Running tests..."
            flutter test || echo "WARNING: No tests found or tests failed"
        is_always_run: false
    
    - save-dart-cache@1: {}
    
    - script@1:
        title: Setup Firebase Configuration
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            echo "Setting up Firebase configuration..."
            
            # If google-services.json is base64 encoded in Secrets
            if [ ! -z "$GOOGLE_SERVICES_JSON_BASE64" ]; then
              echo "Decoding google-services.json from Secrets..."
              echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > android/app/google-services.json
              echo "SUCCESS: google-services.json created from Secrets"
            else
              echo "WARNING: Using google-services.json from repository"
            fi
            
            # Verify file exists
            if [ -f "android/app/google-services.json" ]; then
              echo "SUCCESS: google-services.json found"
            else
              echo "ERROR: google-services.json NOT found!"
              exit 1
            fi
        is_always_run: true
    
    - script@1:
        title: Build Android APK (Release)
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            echo "Building Tracker Costs Android APK in RELEASE mode..."
            
            flutter build apk --release --no-tree-shake-icons
            
            APK_PATH="build/app/outputs/flutter-apk/app-release.apk"
            
            if [ -f "$APK_PATH" ]; then
              echo "SUCCESS: APK built successfully!"
              echo "APK info:"
              ls -lh "$APK_PATH"
              
              # Get APK size
              APK_SIZE=$(du -h "$APK_PATH" | cut -f1)
              echo "Size: $APK_SIZE"
              
              # Export for Firebase
              envman add --key ANDROID_APK_PATH --value "$BITRISE_SOURCE_DIR/$APK_PATH"
              
              # Copy to deploy dir with version
              BUILD_NAME="TrackerCosts_v1.0.0_build${BITRISE_BUILD_NUMBER}.apk"
              cp "$APK_PATH" "$BITRISE_DEPLOY_DIR/$BUILD_NAME"
              echo "APK copied to artifacts as: $BUILD_NAME"
            else
              echo "ERROR: APK not found at $APK_PATH!"
              exit 1
            fi
    
    - script@1:
        title: Verify Firebase App ID
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            echo "Checking Firebase App Distribution configuration..."
            echo "========================================"
            echo "App ID: ${FIREBASE_APP_ID_ANDROID:0:20}..."
            echo "APK Path: $ANDROID_APK_PATH"
            echo "Build Number: $BITRISE_BUILD_NUMBER"
            echo "Branch: $BITRISE_GIT_BRANCH"
            echo "========================================"
            
            # Validate Firebase App ID
            if [ -z "$FIREBASE_APP_ID_ANDROID" ]; then
              echo "ERROR: FIREBASE_APP_ID_ANDROID is not set!"
              echo "Please add it in Bitrise Secrets:"
              echo "1. Go to Bitrise > Workflow Editor > Secrets"
              echo "2. Add: FIREBASE_APP_ID_ANDROID = 1:98211696497:android:6829066851715285e630d0"
              exit 1
            fi
            
            # Validate Firebase Token
            if [ -z "$FIREBASE_TOKEN" ]; then
              echo "ERROR: FIREBASE_TOKEN is not set!"
              echo "Generate token: firebase login:ci"
              exit 1
            fi
            
            # Validate APK
            if [ ! -f "$ANDROID_APK_PATH" ]; then
              echo "ERROR: APK file not found at $ANDROID_APK_PATH"
              exit 1
            fi
            
            echo "SUCCESS: All Firebase configurations are valid"
    
    - script@1:
        title: Deploy to Firebase App Distribution
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -ex
            
            echo "Deploying Tracker Costs to Firebase App Distribution..."
            echo "========================================"
            echo "APK: $ANDROID_APK_PATH"
            echo "App ID: $FIREBASE_APP_ID_ANDROID"
            echo "Branch: $BITRISE_GIT_BRANCH"
            echo "Build: #$BITRISE_BUILD_NUMBER"
            echo "Commit: ${GIT_CLONE_COMMIT_HASH:0:7}"
            echo "========================================"
            
            # Verify APK exists
            if [ ! -f "$ANDROID_APK_PATH" ]; then
              echo "ERROR: APK file not found!"
              exit 1
            fi
            
            # Install Firebase CLI
            echo "Installing Firebase CLI..."
            npm install -g firebase-tools
            
            # Check Firebase CLI version
            firebase --version
            
            # Prepare release notes
            RELEASE_NOTES="Tracker Costs - Expense Tracker App
            
            Build Information:
            - Version: 1.0.0
            - Build Number: #$BITRISE_BUILD_NUMBER
            - Branch: $BITRISE_GIT_BRANCH
            - Commit: ${GIT_CLONE_COMMIT_HASH:0:7}
            - Built: $(date +'%Y-%m-%d %H:%M:%S')
            
            Features:
            - Firebase Firestore integration
            - Real-time expense tracking
            - User authentication (Email/Google)
            - Monthly budget management
            - Category-based expenses
            - Analytics & Crashlytics
            
            Firebase Services:
            - Firestore Database
            - Firebase Auth
            - Firebase Analytics
            - Firebase Crashlytics
            
            Installation:
            1. Download from Firebase App Distribution
            2. Enable Unknown Sources on Android
            3. Install APK
            4. Login with your account
            
            Test the following:
            - Login/Register functionality
            - Add/Edit/Delete expenses
            - Real-time data sync
            - Budget tracking
            - Category filtering"
            
            # Upload to Firebase App Distribution
            echo "Starting upload to Firebase..."
            firebase appdistribution:distribute "$ANDROID_APK_PATH" \
              --app "$FIREBASE_APP_ID_ANDROID" \
              --token "$FIREBASE_TOKEN" \
              --groups "testers" \
              --release-notes "$RELEASE_NOTES" \
              --debug
            
            EXIT_CODE=$?
            
            if [ $EXIT_CODE -eq 0 ]; then
              echo "======================================="
              echo "Successfully deployed to Firebase App Distribution!"
              echo "Testers in 'testers' group will receive email notification"
              echo "Check Firebase Console for distribution status"
              echo "========================================"
            else
              echo "======================================="
              echo "Firebase upload failed with exit code: $EXIT_CODE"
              echo "Troubleshooting:"
              echo "1. Verify FIREBASE_TOKEN is valid (run: firebase login:ci)"
              echo "2. Check FIREBASE_APP_ID_ANDROID matches your app"
              echo "3. Ensure 'testers' group exists in Firebase Console"
              echo "4. Check Firebase Console > App Distribution for errors"
              echo "========================================"
              exit $EXIT_CODE
            fi
    
    - script@1:
        title: Generate Build Report
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            cat > "$BITRISE_DEPLOY_DIR/BUILD_REPORT.md" <<EOF
            # Tracker Costs - Build Report
            
            ## Build Information
            - Version: 1.0.0
            - Package: com.example.tracker_costs
            - Build: #$BITRISE_BUILD_NUMBER
            - Branch: $BITRISE_GIT_BRANCH
            - Commit: ${GIT_CLONE_COMMIT_HASH:0:7}
            - Date: $(date +'%Y-%m-%d %H:%M:%S')
            
            ## Firebase Services
            - Firestore Database: Enabled
            - Firebase Auth: Enabled
            - Firebase Analytics: Enabled
            - Firebase Crashlytics: Enabled
            - App Distribution: Deployed
            
            ## Features
            - User Authentication (Email/Password, Google)
            - Real-time Expense Tracking
            - Monthly Budget Management
            - Category-based Filtering
            
            ## Testing Checklist
            - [ ] Login/Register
            - [ ] Add/Edit/Delete expenses
            - [ ] Real-time sync
            - [ ] Budget calculations
            - [ ] Category filtering
            EOF
            
            echo "Build report created"
    
    - script@1:
        title: Create Installation Instructions
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -e
            
            cat > "$BITRISE_DEPLOY_DIR/INSTALL_INSTRUCTIONS.txt" <<'EOF'
            ============================================================
            Tracker Costs - Installation Guide
            ============================================================
            
            METHOD 1: Firebase App Distribution (RECOMMENDED)
            1. Check email for Firebase invitation
            2. Install Firebase App Tester from Play Store
            3. Open invitation link and download app
            
            METHOD 2: Manual APK Installation
            1. Download APK to Android device
            2. Enable: Settings > Security > Unknown Sources
            3. Open APK file and install
            
            METHOD 3: ADB Installation (Developers)
            1. Enable USB Debugging on device
            2. Connect device to computer
            3. Run: adb install TrackerCosts_v1.0.0.apk
            
            TROUBLESHOOTING:
            - "App not installed": Uninstall old version first
            - "Can't login": Check internet connection
            - "Data not syncing": Logout and login again
            
            For support, contact the development team.
            ============================================================
            EOF
            
            echo "Installation instructions created"
    
    - deploy-to-bitrise-io@2:
        inputs:
        - notify_user_groups: none
        - is_compress: 'false'

meta:
  bitrise.io:
    stack: linux-docker-android-22.04