// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAoK7yMM2KoQ5g-c9uq-cYjxWI8Bn_Q9M',
    appId: '1:98211696497:web:9c103e3c7d62367ae630d0',
    messagingSenderId: '98211696497',
    projectId: 'tracker-costs',
    authDomain: 'tracker-costs.firebaseapp.com',
    storageBucket: 'tracker-costs.firebasestorage.app',
    measurementId: 'G-D9BE29BXPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1aAIT2hbcaVtweO3JqBwtMDKqAoTln-0',
    appId: '1:98211696497:android:6829066851715285e630d0',
    messagingSenderId: '98211696497',
    projectId: 'tracker-costs',
    storageBucket: 'tracker-costs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2mXY_n7qpknpSJbqu6ZTq_o9zdxzeXTw',
    appId: '1:98211696497:ios:33128efec417808fe630d0',
    messagingSenderId: '98211696497',
    projectId: 'tracker-costs',
    storageBucket: 'tracker-costs.firebasestorage.app',
    iosBundleId: 'com.example.trackerCosts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2mXY_n7qpknpSJbqu6ZTq_o9zdxzeXTw',
    appId: '1:98211696497:ios:33128efec417808fe630d0',
    messagingSenderId: '98211696497',
    projectId: 'tracker-costs',
    storageBucket: 'tracker-costs.firebasestorage.app',
    iosBundleId: 'com.example.trackerCosts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAoK7yMM2KoQ5g-c9uq-cYjxWI8Bn_Q9M',
    appId: '1:98211696497:web:dcd4f449fa33766be630d0',
    messagingSenderId: '98211696497',
    projectId: 'tracker-costs',
    authDomain: 'tracker-costs.firebaseapp.com',
    storageBucket: 'tracker-costs.firebasestorage.app',
    measurementId: 'G-VK4P9H96G6',
  );
}
